services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure
    env_file:
      - .env
    networks:
      - triz

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - triz

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - triz

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbouyahy/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mbouyahy/data/wordpress

networks:
  triz:
    driver: bridge
