FROM debian:buster

# RUN apk update && apk upgrade && apk add --no-cache mariadb mariadb-client
RUN apt update && \
	apt install -y mariadb-server && \
	apt autoremove && \
	apt clean && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# RUN mkdir -p /run/mysqld && \
# 	chmod 777 /run/mysqld

# RUN sed -i "s|skip-networking|#skip-networking|g" /etc/my.cnf.d/mariadb-server.cnf
# RUN echo "datadir = /var/lib/mysql" >> /etc/my.cnf.d/mariadb-server.cnf
# RUN sed -i "s|bind-address            = 127.0.0.1|bind-address            = 0.0.0.0|g" /etc/mysql/mariadb.conf.d/50-server.cnf
# RUN sed -i "s|skip-networking|#skip-networking|g" /etc/mysql/mariadb.conf.d/50-server.cnf

# RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql --skip-test-db

# RUN mysql_install_db --user=mysql --skip-name-resolve --force

# COPY /var/lib/mysql/mysql.sock /var/lib/mysql/mysql.sock.bak

# RUN chmod 777 /var/lib/mysql/mysql
# RUN chmod 777 /var/lib/mysql

COPY ./dependencies/script.sh /script.sh

EXPOSE 3306

# RUN mkdir -p /var/run/mysqld \
# 	&& chown -R mysql:mysql /var/run/mysqld \
# 	&& chmod 777 /var/run/mysqld

# RUN chmod 777 ./dependencies/my.cnf

# COPY ./dependencies/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

RUN rm -rf /var/lib/mysql/mysql

# RUN chmod 644 /etc/mysql/my.cnf
# RUN chmod 644 /etc/mysql/mariadb.conf.d/50-server.cnf
RUN chown -R mysql:mysql /var/lib/mysql/
RUN chmod -R 755 /var/lib/mysql/
RUN chmod -R 755 /etc/mysql/conf.d
RUN chmod -R 644 /var/lib/mysql/*


# RUN rm -rf /var/lib/mysql/*

# ENTRYPOINT ["/etc/init.d/mysql", "start"]

ENTRYPOINT ["sh", "script.sh"]

# CMD ["mysqld_safe", "--skip-grant-tables&"]
CMD ["mariadb", "--user=mysql", "--bind-address=0.0.0.0"]
# CMD ["mariadbd" ,"--user=root", "--bootstrap"]